test rds

diff --git a/.github/workflows/workflow-rds.yml b/.github/workflows/workflow-rds.yml
--- a/.github/workflows/workflow-rds.yml
+++ b/.github/workflows/workflow-rds.yml
@@ -101,31 +101,44 @@ jobs:
           source: "./.env"
           target: "~/"
 
-
-      - name: Set up SSH
-        uses: appleboy/ssh-action@v0.1.5
+      - name: ls -a via ssh
+        uses: fifsky/ssh-action@master
         with:
-          host: ${{ secrets.AWS_HOST }}
-          username: ${{ secrets.AWS_ACCOUNT }}
-          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            # Automatically accept host key
-            mkdir -p ~/.ssh
-            ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
-            
-            whoami
-                  
+          command: |
             cd ~
             ll
             sudo docker compose -f docker-compose-rds-prod.yml  up -d
-            # Check if docker-compose up was successful
-            if [ $(sudo docker compose ps -q backend_rds) ]; then
-              echo "Docker containers are up and running."
-            else
-              echo "Docker-compose failed. Exiting."
-              exit 1
-            fi
+          host: ${{ secrets.AWS_HOST }}
+          user: root
+          key: ${{ secrets.AWS_SSH_PRIVATE_KEY}}
+
+
+      
+      
+      # - name: Set up SSH
+      #   uses: appleboy/ssh-action@v0.1.5
+      #   with:
+      #     host: ${{ secrets.AWS_HOST }}
+      #     username: ${{ secrets.AWS_ACCOUNT }}
+      #     key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
+      #     port: 22
+      #     script: |
+      #       # Automatically accept host key
+      #       mkdir -p ~/.ssh
+      #       ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
+            
+      #       whoami
+                  
+      #       cd ~
+      #       ll
+      #       sudo docker compose -f docker-compose-rds-prod.yml  up -d
+      #       # Check if docker-compose up was successful
+      #       if [ $(sudo docker compose ps -q backend_rds) ]; then
+      #         echo "Docker containers are up and running."
+      #       else
+      #         echo "Docker-compose failed. Exiting."
+      #         exit 1
+      #       fi
   
       # - name: Push code to repository if docker-compose up is successful
       #   if: ${{ success() }}
