test CD

diff --git a/.github/workflows/workflow-rds.yml b/.github/workflows/workflow-rds.yml
--- a/.github/workflows/workflow-rds.yml
+++ b/.github/workflows/workflow-rds.yml
@@ -79,7 +79,7 @@ jobs:
       - uses: mikefarah/yq@master
         with:
           cmd: |
-          yq e '.services.backend_rds |= {"image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}", .}' -i docker-compose.yml
+            yq e '.services.backend_rds |= {"image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}"} + .' -i docker-compose-rds-prod.yml
 
       
       
@@ -89,7 +89,7 @@ jobs:
           host: ${{ secrets.AWS_HOST }}
           username: ${{ secrets.AWS_ACCOUNT }}
           key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
-          source: "./docker-compose.yml"
+          source: "./docker-compose-rds-prod.yml"
           target: "~/"
 
       - name: Copy file from runner to remote VM
@@ -113,27 +113,27 @@ jobs:
             # Automatically accept host key
             mkdir -p ~/.ssh
             ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
-            whoami
             
-      
+            whoami
+                  
             cd ~
             ll
-            sudo docker compose up -d
-            # # Check if docker-compose up was successful
-            # if [ $(sudo docker compose ps -q backend_rds) ]; then
-            #   echo "Docker containers are up and running."
-            # else
-            #   echo "Docker-compose failed. Exiting."
-            #   exit 1
-            # fi
+            sudo docker compose -f docker-compose-rds-prod.yml  up -d
+            # Check if docker-compose up was successful
+            if [ $(sudo docker compose ps -q backend_rds) ]; then
+              echo "Docker containers are up and running."
+            else
+              echo "Docker-compose failed. Exiting."
+              exit 1
+            fi
   
-      - name: Push code to repository if docker-compose up is successful
-        if: ${{ success() }}
-        run: |
-          git config --global user.name "GitHub Actions"
-          git config --global user.email "actions@github.com"
-          git commit -am "Update docker-compose.yml ${{ env.COMMIT_TAG }}"
-          git push 
+      # - name: Push code to repository if docker-compose up is successful
+      #   if: ${{ success() }}
+      #   run: |
+      #     git config --global user.name "GitHub Actions"
+      #     git config --global user.email "actions@github.com"
+      #     git commit -am "Update docker-compose.yml ${{ env.COMMIT_TAG }}"
+      #     git push 
 
           
       
