Update workflow-rds.yml

diff --git a/.github/workflows/workflow-rds.yml b/.github/workflows/workflow-rds.yml
--- a/.github/workflows/workflow-rds.yml
+++ b/.github/workflows/workflow-rds.yml
@@ -7,46 +7,46 @@ env:
       IMAGE_NAME: ${{ vars.IMAGE_NAME_RDS }}
 
 jobs:
-  ci:
-    name: CI
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          ref: 'workflows'
-          fetch-depth: 0
+  # ci:
+  #   name: CI
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         ref: 'workflows'
+  #         fetch-depth: 0
 
-      - name: Set up AWS CLI
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+  #     - name: Set up AWS CLI
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Log in to Amazon ECR
-        run: |
-          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
+  #     - name: Log in to Amazon ECR
+  #       run: |
+  #         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
 
       
-      # Step 4: Get short Git commit hash and the commit tag
-      - name: Get commit tag and short hash
-        id: vars
-        run: |
-          echo "COMMIT_TAG=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+  #     # Step 4: Get short Git commit hash and the commit tag
+  #     - name: Get commit tag and short hash
+  #       id: vars
+  #       run: |
+  #         echo "COMMIT_TAG=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
       
-      - name: Build Docker Image
-        run: |
-          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:${{ env.COMMIT_TAG }} ./$IMAGE_NAME
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:${{ env.COMMIT_TAG }} ./$IMAGE_NAME
 
-      - name: Push Docker Image to ECR
-        run: |
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:${{ env.COMMIT_TAG }}
+  #     - name: Push Docker Image to ECR
+  #       run: |
+  #         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:${{ env.COMMIT_TAG }}
           
 
   cd:
     name: CD
-    needs: ci
+    # needs: ci
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -55,16 +55,16 @@ jobs:
           ref: 'workflows'
           fetch-depth: 0
 
-      - name: Set up AWS CLI
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+      # - name: Set up AWS CLI
+      #   uses: aws-actions/configure-aws-credentials@v1
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Log in to Amazon ECR
-        run: |
-          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
+      # - name: Log in to Amazon ECR
+      #   run: |
+      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
 
       
       # Step 4: Get short Git commit hash and the commit tag
@@ -112,14 +112,15 @@ jobs:
             
       
             cd ~
+            ll
             sudo docker compose up -d
-            # Check if docker-compose up was successful
-            if [ $(sudo docker compose ps -q backend_rds) ]; then
-              echo "Docker containers are up and running."
-            else
-              echo "Docker-compose failed. Exiting."
-              exit 1
-            fi
+            # # Check if docker-compose up was successful
+            # if [ $(sudo docker compose ps -q backend_rds) ]; then
+            #   echo "Docker containers are up and running."
+            # else
+            #   echo "Docker-compose failed. Exiting."
+            #   exit 1
+            # fi
   
       - name: Push code to repository if docker-compose up is successful
         if: ${{ success() }}
